### ISSUE TITLE
Theme selection form flickers badly on page load

### ISSUE THREAD

**Issue by manu37** [cmb69/themeswitcher_xh#16]
Why not control it over css?
[patch.zip](https://github.com/cmb69/themeswitcher_xh/files/1266977/patch.zip)

**Comment by cmb69** [comment]
Because `<noscript>` is broken by design.  See https://perma.cc/5SBR-58CD why it's bad to use it nowadays. TL;DR: there are likely more people having JS enabled, but don't actually get it, than users having no JS support in the first place.

If at all, the script could be written to `$hjs` instead of `$bjs` which should reduce the flickering at the cost of generally slower page speed.

Anyhow, do you have an example page where this behavior can be seen? Does it happen only with slow internet connections? Is it a browser specific issue? Would it help to set `visibility: hidden` instead of `display: none`?

**Comment by manu37** [comment]
It is no matter of low bandwith. I test on localhost. I could try to insert the code in $hjs. But not today.

**Comment by cmb69** [comment]
Hm, never noticed anything in Chrome, but sometimes the button is visible for a short (but too long) time in Firefox 55. Will do some further testing.

**Comment by cmb69** [comment]
Well, no further testing needed. The problem is that DOMContentLoaded could be triggered *long* after the initial page is displayed. Since Themeswitcher_XH's JS is so minimal, it appears to be best to put it directly into the HTML – some ~~recommend~~ discourage putting JS into HTML, but *in this case* it appears to be the simplest and most effective solution (lesson learned!)
